### PR TITLE
pointing to web.archive.org cache of ECMA-357 because current link redirects to spec for ECMA-375 – "Case for 120 mm HVD-ROM disk"

### PR DESCRIPTION
**Pull request by antialias**

### CODE REVIEW

**Comment by spicyj** [comment]
Wow weird. Maybe we should just link to http://www.ecma-international.org/publications/files/ECMA-ST-WITHDRAWN/Ecma-357.pdf?

**Comment by RReverser** [comment]
Um... ECMAScript standard numbers are not constant?

**Comment by spicyj** [comment]
@RReverser It redirects to 375, presumably because 357 was deleted?

**Comment by RReverser** [comment]
@spicyj  That doesn't really explain where it disappeared and why one spec might redirect to completely irrelevant another :/

**Comment by antialias** [comment]
Now linking to PDF for ECMA-357 instead of web.archive.org's cache

**Pull request merged**
