### PR TITLE
Update transpilers

### PR DESCRIPTION
**Pull request by kuraga**

### CODE REVIEW

**Comment by RReverser** [comment]
Why did you remove other two? They're cool and used in some places as well.

**Comment by kuraga** [comment]
@RReverser ,
Last commit of `JSXDOM` is July, 2013. It's unmantained (and doesn't comply current document?).
`mercury-jsxify` isn't mantained by @Raynos, see https://github.com/Raynos/mercury/issues/143#issuecomment-75398749

**Comment by RReverser** [comment]
@kuraga Well, at least I know teams using JSXDOM (they don't use React, but find JSX syntax for creating DOM nodes much cleaner than regular DOM API) and there's not much to be added to it since primary functionality is already implemented.

**Comment by kuraga** [comment]
@RReverser , feel free to use provided commits in right manner. Thanks.

**Pull request merged**
