### PR TITLE
invalid type of attribute value

### PR DESCRIPTION
**Pull request by fxbois**
after discussion with @vjeux

### CODE REVIEW

**Comment by vjeux** [comment]
cc @syranide @sebmarkbage

**Comment by syranide** [comment]
+1 Yep that should be correct.

**Comment by sebmarkbage** [comment]
Actually that's not current. We explicitly decided to allow this in the syntax but never implemented it in React transpiler. We should be parsing it correctly though:

https://github.com/facebook/esprima/blob/fb-harmony/esprima.js#L7000

**Comment by RReverser** [comment]
Yeah, this is parsed correctly and supported for transpiling in Babel. If we want to remove it, I believe we need some separate issue for discussion prior to the PR.

**Pull request closed without merging**
